### ISSUE TITLE
AWS EventBridge Cron expressions validation

### ISSUE THREAD

**Issue by jesusenlanet** [vcoder4c/cron-validator#10]
Hi all,

Thanks for this package, it looks amazing and helped me to avoid to reinvent the wheel.

I found a use case that I want to request as feature (if possible) for this package, AWS EventBridge cron expressions, which are similar to, but not compatible with unix cron expressions:
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html#eb-cron-expressions

Many thanks in advance.

**Comment by vcoder4c** [comment]
I think it's possible to support for this case. Something like:
```
scheduler = CronScheduler(cron_string, version=[UNIX, EB])
```

The default value can be UNIX for backward compatible. But I am quite busy recently, anyone can help?

**Comment by mmasztalerczuk** [comment]
Hi,

Since I also need support for this syntax (mainly the use of L and W), I tried to implement this functionality into this package. I have published a PR with my changes. 

If you have time take a look and let me know what you think about this implementation.

https://github.com/vcoder4c/cron-validator/pull/11

**Comment by vcoder4c** [comment]
Now, we can use v1.0.6 for this purpose.
